# Generated by Django 4.0.1 on 2023-01-08 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(blank=True)),
                ('user', models.CharField(max_length=10000)),
                ('room', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(default='option 1 unavailable', max_length=1000)),
                ('votes', models.IntegerField(default=0)),
                ('percentage_vote', models.FloatField(default=0.0)),
                ('color_code', models.CharField(default='green', max_length=44)),
            ],
        ),
        migrations.CreateModel(
            name='Room_expiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(default=1)),
                ('expiry', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='yes', max_length=100)),
                ('saved', models.ManyToManyField(blank=True, to='chat.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('topic', models.CharField(default='this room deosnt have a topic up for discussion', max_length=1000, null=True)),
                ('total_votes', models.IntegerField(default=0)),
                ('user_count', models.IntegerField(default=0)),
                ('catagory', models.CharField(default='none', max_length=1000)),
                ('time', models.DateTimeField(blank=True)),
                ('opts', models.ManyToManyField(to='chat.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimg', models.ImageField(default='thisone.png', upload_to='static/media/media/images')),
                ('maximum_rooms', models.IntegerField(default=0)),
                ('rooms', models.ManyToManyField(to='chat.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vote', models.ManyToManyField(to='chat.Option')),
                ('voted_rooms', models.ManyToManyField(blank=True, related_name='voted_room', to='chat.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anime', max_length=1000)),
                ('profiles', models.ManyToManyField(blank=True, to='chat.Profile')),
            ],
        ),
    ]
