# Generated by Django 4.0.1 on 2023-01-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room_expiry',
        ),
        migrations.AddField(
            model_name='room',
            name='pfp',
            field=models.ImageField(default='/media/static/media/media/thisone.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='/media/static/media/media/thisone.png', upload_to='static/media/media/images'),
        ),
    ]
