# Generated by Django 4.0.1 on 2023-01-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_room_expiry_room_pfp_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='creator',
            field=models.CharField(default='user not found', max_length=55),
        ),
        migrations.AlterField(
            model_name='room',
            name='pfp',
            field=models.ImageField(default='static/media/media/thisone.png', upload_to=''),
        ),
    ]
